### ISSUE TITLE
Create PR Template - Add checklist to ready a PR for review

### ISSUE THREAD

**Issue by Rulasmur** [MovingBlocks/DestinationSol#134]
Create a template that include a general guide to how a pr should be formatted.
Include a checklist of items that should be satisfied before the PR is submitted.
- [x] check out the .github dir from MovingBlocks/Terasology 

Format ideas:

# Description
> Please describe what this PR does and why it does it
---

# Notes
> Include any extra notes here
---

### Pre Pull Request Checklist:
- [ ] Code has been scanned with SonarLint and has passed[Find it here](http://www.sonarlint.org/intellij/)
- [ ] Methods have been annotated with @ Nullable and @ Nonnull ([Read more](https://github.com/MovingBlocks/DestinationSol/wiki/@Nullable-&-@Nonnull-Quickstart))
- [ ] There are no errors present in the project
- [ ] Code has been formatted and indented
- [ ] Methods have appropriate Javadoc[How to write Javadoc](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html)

----
@Cervator @rzats Any suggestions?

**Comment by rzats** [comment]
For the most part this looks good, though I'd add links to SonarLint and an "appropriate Javadoc" style guide.
