### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by NicholasBatesNZ** [MovingBlocks/DestinationSol#455]
Our current UI system is not very easy to work with and frankly a bit of a bodge (think magic constants, 0-1 percentages of the screen height, etc.). As such it is not very fun, and rather difficult to work with.

### Option 1: Embed NUI from Terasology

This is the preferred option, however it will likely involve the most work.
[Terasology](https://github.com/MovingBlocks/Terasology) has a fantastic UI library, however it is still embedded within the main engine. Work must first be done to extract NUI from Terasology (see https://github.com/MovingBlocks/Terasology/issues/2307) and then DS would be adapted to use it.

- [x] Resolve dependencies in https://github.com/MovingBlocks/Terasology/issues/2307
- [x] Extract NUI into standalone library
- [x] Adapt Destination Sol to use it
- [x] Port over screens

### ~~Option 2: Revive uiOverhaul~~

There was an attempt at solving these issues which lies in the [`uiOverhaul`](https://github.com/MovingBlocks/DestinationSol/tree/uiOverhaul) branch, however it grew old and stale after months of not receiving the love it deserved (see conflicts in #443 and many screens were not ported over). There were also some [PRs into it](https://github.com/MovingBlocks/DestinationSol/pulls?&q=label%3AUIOverhaul+) (with the `uiOverhaul` label) to port over more screens but they were not seen to, under the expectation that `uiOverhaul` was dying.

This option involves reviving and finishing the `uiOverhaul` effort.

- [ ] ~~Rebase `uiOverhaul`~~
- [ ] ~~Fix any bugs~~
- [ ] ~~Merge the [PRs into it](https://github.com/MovingBlocks/DestinationSol/pulls?&q=label%3AUIOverhaul+) where appropriate~~
- [ ] ~~Fix any more bugs~~
- [ ] ~~Port over any remaining screens~~

### ~~Option 3: Start a new UI Overhaul~~

Start from scratch replacing the current UI system with something better.
 
### Todo before closing issue

- [ ] Delete `uiOverhaul` branch
- [ ] Delete `uiOverhaul` label

**Comment by Cervator** [comment]
On a related note: it would be nice to support sliders for some of the UI settings after a conversion, such as for sound volume

**Comment by CoffeeSF** [comment]
21:9 / 2560x1080
First-time startup in windowed mode

Video:
[https://cdn.discordapp.com/attachments/389093174921920512/733357135555067924/vid.mp4](url)

Images:

![image](https://user-images.githubusercontent.com/34051081/87698439-7bbd9a80-c761-11ea-809d-4a34f8beb13d.png)
![image](https://user-images.githubusercontent.com/34051081/87698454-7fe9b800-c761-11ea-8cce-816c360454f8.png)


Going into fullscreen mode does **not** fix it.
Restarting from windowed mode does **not** fix it.
Restarting from fullscreen mode fixes it.
Going from fullscreen mode back to the windowed mode when it was fixed produces this (Slightly misaligned).

![image](https://user-images.githubusercontent.com/34051081/87698518-96900f00-c761-11ea-80ac-e181750ad846.png)
![image](https://user-images.githubusercontent.com/34051081/87698529-9a239600-c761-11ea-851e-84dead8ae372.png)

Going to fullscreen mode from above fixes it without a restart.

Examples of fixed GUI

![image](https://user-images.githubusercontent.com/34051081/87699166-79a80b80-c762-11ea-93f9-e8815d7011ee.png)
![image](https://user-images.githubusercontent.com/34051081/87699181-7e6cbf80-c762-11ea-9704-c0fbf9f75d2f.png)

**Comment by Adrijaned** [comment]
Aaand we have NUI!

**Comment by BenjaminAmos** [comment]
I think this is done now? All the significant NUI screens were ported over in #632. Any other miscellaneous UI improvements would be better-off in their own separate issues.

Having worked with NUI for a while now, I wouldn't call it fantastic. It's a fair bit better than what we had before though.
