### ISSUE TITLE
32-bit Linux Isn't Supported in LWJGL3

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#477]
## Overview
Credit goes to @NicholasBatesNZ for finding this.
See below for the detailed bug report.

### Summary
PR #360 upgraded the LibGDX backend from LWJGL2 to LWJGL3. The side effect of this is that 32-bit Linux is [no longer supported](https://github.com/LWJGL/lwjgl3/issues/162). As far as I'm concerned, it is fine that we don't support 32-bit Linux, but there are a few things that we need to do for the version 2 release to ensure 64-bit Linux is supported.

### Tasks
- [x] Update the launch options in Steam to use the `sol64.sh` script instead of `sol.sh`. This should resolve the initial bug report below. (Or change `sol.sh` to use the 64-bit JRE).
- [x] Update the system requirements on the Steam Store page to state that only 64-bit Linux is supported. 
- [x] Do we also update the graphics card requirements to state OpenGL 3.0 compatible? Is LWJGL3 using OpenGL 3.0?
- [x] Remove 32-bit Linux references from the repo. This includes the `sol.sh` script and the associated JRE / script to download 32-bit Linux JRE.

### What you were trying to do
Run the Steam Private Beta of Destination Sol on Linux

### What actually happened
The game wouldn't start with error:
`Failed to locate library: liblwjgl32.so`

### How to reproduce

* Obtain a distribution build of version 2.0 of Destination Sol. Either from the Steam Beta, or [Jenkins](http://jenkins.terasology.org/view/DestSol/job/DestinationSol/), or build it locally. 
* Make sure you are on a Linux distro
* Start the game using the `sol.sh` script

### Log details and game version
![Linux32](https://user-images.githubusercontent.com/7613950/74487301-fcaf0680-4f23-11ea-9c76-c0c5bfd1a79c.png)

### Computer details
Ubuntu 18.04

**Comment by SimonC4** [comment]
LWJGL3 isn't the same as OpenGL 3.0. We are still using OpenGL 2.0 so that task isn't relevant.

**Comment by SimonC4** [comment]
Updated the minimum requirements on Steam to state it "Requires a 64-bit processor and operating system".
