### ISSUE TITLE
Adapt existing UI screens to use NUI

### ISSUE THREAD

**Issue by BenjaminAmos** [MovingBlocks/DestinationSol#632]
As part of #455, the existing built-in UI system is being replaced with the NUI framework from Terasology. This issue tracks the progess made in adapting all of the existing screens to use NUI.
- [ ] [TutorialManager](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/ui/TutorialManager.java) (#670 - Moved to `Tutorial Screen)
- [X] [CreditsScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/menu/CreditsScreen.java) (#631)
- [X] ConsoleScreen (was done as part of #536)
- [ ] [InventoryOperationsScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/game/screens/InventoryOperationsScreen.java) and its sub-classes (#668)
- [X] [LoadingScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/menu/LoadingScreen.java) (#631)
- [X] [NewGameScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/menu/NewGameScreen.java) (#631)
- [ ] [MenuScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/game/screens/MenuScreen.java) (#666)
- [ ] [WaypointCreationScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/game/screens/WaypointCreationScreen.java) (#669)
- [X] [ResolutionScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/menu/ResolutionScreen.java) (#631)
- [ ] [TalkScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/game/screens/TalkScreen.java) (#667)
- [X] [NewShipScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/menu/NewShipScreen.java) (#631)
- [X] [OptionsScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/menu/OptionsScreen.java) (#631)
- [X] [MainMenuScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/menu/MainMenuScreen.java) (#631)
- [ ] [MapScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/game/screens/MapScreen.java) (#669)
- [X] [InputMapScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/menu/InputMapScreen.java) (#631)
- [ ] [InventoryScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/game/screens/InventoryScreen.java) (#668)
- [ ] [MainGameScreen](https://github.com/MovingBlocks/DestinationSol/blob/develop/engine/src/main/java/org/destinationsol/game/screens/MainGameScreen.java) (see #588 for a partial port and #665 for the rest)
